export default {
  LOAD_CONTESTS: "LOAD_CONTESTS",
  LOAD_UNIS: "LOAD_UNIS",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
};
